services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NITSAN\NsNewsAdvancedsearch\EventListener\ModifyFlexformEvent:
      tags:
          - name: event.listener
            identifier: 'flexParsing'
            event: TYPO3\CMS\Core\Configuration\Event\AfterFlexFormDataStructureParsedEvent