services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NITSAN\NsNewsAdvancedsearch\EventListener\ModifyFlexformEvent:
      tags:
          - name: event.listener
            identifier: 'flexParsing'
            event: TYPO3\CMS\Core\Configuration\Event\AfterFlexFormDataStructureParsedEvent

  NITSAN\NsNewsAdvancedsearch\Utility\ClassCacheManager:
    arguments: ['@news.cache']
    public: true

  NITSAN\NsNewsAdvancedsearch\Utility\ClassLoader:
    arguments: ['@news.cache', '@NITSAN\NsNewsAdvancedsearch\Utility\ClassCacheManager']
    public: true
